// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:679e75fa-1129-4246-9ed3-4dc6a212804f",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_C8d0GaPAr",
    "aws_user_pools_web_client_id": "59cmrblhd18fblhb2nb67mnhqm",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://i63dvhg5gnga3essjvez4gbk24.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
